language: c

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

os:
  - osx
  - linux

env:
  global:
   - MAKEFLAGS="-j8"

addons:
  apt:
    packages:
      - gfortran
      - autoconf
      - automake
      - libtool
      - libtool-bin
      - mpich
      - libmpich-dev
    update: true
    # apt-package-whitelist can be found in
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise


before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - test -n $CC && unset CC
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install mpich; fi
  - autoconf --version
  - automake --version
  - if [ $TRAVIS_OS_NAME = linux ]; then libtool --version ; else libtool -V ; fi
  - mpichversion
  - autoreconf -i

script:
  - ./configure --silent
  # - if [[ "${TRAVIS_OS_NAME}" = "linux" ]] ; then make distcheck -s V=1 LIBTOOLFLAGS=--silent DISTCHECK_CONFIGURE_FLAGS="--silent --enable-profiling --enable-subfiling --enable-thread-safe --enable-burst_buffering --enable-shared --enable-debug pnc_ac_debug=yes" ; fi
  # - if [[ "${TRAVIS_OS_NAME}" = "osx" ]] ; then make -s V=1 LIBTOOLFLAGS=--silent check ; fi
  # - make -s V=1 LIBTOOLFLAGS=--silent check
  # - make -s V=1 LIBTOOLFLAGS=--silent ptest
  - if [[ "${TRAVIS_OS_NAME}" = "linux" ]] ; then make distcheck -s V=1 LIBTOOLFLAGS=--silent DISTCHECK_CONFIGURE_FLAGS="--enable-profiling --enable-subfiling --enable-thread-safe --enable-burst_buffering --enable-shared pnc_ac_debug=yes CFLAGS=-O3 CXXFLAGS=-O3 FCFLAGS=-O3 FFLAGS=-O3" ; fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]] ; then make distcheck -s V=1 LIBTOOLFLAGS=--silent DISTCHECK_CONFIGURE_FLAGS="--enable-profiling --enable-subfiling --enable-thread-safe --enable-burst_buffering --enable-shared pnc_ac_debug=yes CFLAGS=-O3" ; fi


after_success:
  - make -s distclean

after_failure:
  - cat ./config.log
  - make -s distclean

notifications:
  email: false

# to build all branches
branches:
  only:
  - master
  - /.*/
